### ISSUE TITLE
Subject in alphabetical order in Shanoir

### ISSUE THREAD

**Issue by ebannier2018** [fli-iam/shanoir-ng#707]
Hi, 

The subject are listed in Shanoir using the examination date, chronologically. 
Could you list them in alphabetical order instead ? 
Thanks in advance

Elise

**Comment by ocommowi** [comment]
This also applies to datasets and subjects lists in the search left panel, it is difficult to select search items if not listed alphabetically

**Comment by cmaumet** [comment]
Discussed on Dec 11 as a critical bug.

**Comment by jcomedouteau** [comment]
I'm on it.

Could you describe us the Menus / Items where it should apply? Starting point:

- Study detail => Subject tree
- Study edit => list of participants in select list (discussed with MDjoat)

- Subject list => @ocommowi For the search list, it is actually possible to order by name by clicking on the top column reference "common name"
![image](https://user-images.githubusercontent.com/7604176/102064785-08937f80-3df8-11eb-87cb-8820fdb15f5e.png)


Should we apply this to something else (Centers? Exams ? Other?) ? @ebannier2018 @cmaumet 
Jean-Côme

**Comment by ocommowi** [comment]
I was more talking on the left side search column in my comment (see screenshot where it is not alphabetically sorted). But thanks for the advice on the search results.

![Screenshot 2020-12-14 at 11 00 00](https://user-images.githubusercontent.com/2983208/102067558-90c75400-3dfb-11eb-9421-157e1a8133bb.png)

**Comment by jcomedouteau** [comment]
Oh yes I see ! The subjects here are ordered by number of results, we'll discuss this in another issue as we are re-thinking all solr search UI.
You can make a simple search here in the search bar on the top of each criteria:
![image](https://user-images.githubusercontent.com/7604176/102068090-4f837400-3dfc-11eb-9cb9-98d3f06b0bf6.png)

Jean-Côme

**Comment by cmaumet** [comment]
Hi @jcomedouteau - I *think* Elise (please will correct me if I'm wrong) was referring to the list of "sequences"/images : under subjects, under a given subject, under an exam (that starts with a date), the list of dataset aquisition should be in alphabetic order. 

Does that make sense?

(Sorry I don't want to paste a screenshot here for privacy reason but can share by email if that helps, let me know)

**Comment by ebannier2018** [comment]
Sorry for not being specific enough. I meant Study detail >> Subject tree 
The issue with the sequence order is separate.

**Comment by jcomedouteau** [comment]
@cmaumet , I think this was another subject :https://github.com/fli-iam/shanoir-ng/issues/534
Thanks @ebannier2018

**Comment by yyao1231** [comment]
Hi @ebannier2018! I talked to Jean-Côme this afternoon. He made some corrections and I think it is already done on qualif. (I tested the the study details > subject tree part.) Could you confirm that it is resolved? If so, we could close the issue.

**Comment by ebannier2018** [comment]
Hi, 

I talked with Jean Come yesterday morning to test together and determine what was and what was still not working. 
1. the common name was used to sort the subject but the subject identifier for this study was displayed. This was also reported when importing a new examination (the list of subject is not alphabetical). 
2. As for the series in the examination, all the examinations after the deploy are ordered correctly but not those imported before. 
Thereby I noticed that some imports had not been anonymized correctly. I will get in touch with the user to have him import the data again. 

Elise 

-------------------------------------------------- 
MRI Physicist, PhD 
Plate-forme NeurInfo, https://www.neurinfo.org/ 
CHU Rennes, https://www.chu-rennes.fr/ 
Unité Empenn (ex-VISAGES) U1228 INSERM-INRIA, IRISA UMR CNRS 6074, https://team.inria.fr/empenn/ 
Membre du Réseau d'Entraide Multicentrique en IRM, https://remi.network/fr/ et de la SFRMBM, https://sfrmbm.fr/ 

+33 2 99 28 99 06 (Neurinfo) 
+33 2 99 84 22 13 (Empenn) - Fridays

**Comment by michaelkain** [comment]
will be tested by Elise

**Comment by ebannier** [comment]
I tested for a few studies and the subjects are now listed in alphabetical order. Thanks a lot.
